// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerHouse.Models;

#nullable disable

namespace PowerHouse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503175917_GymPhotos")]
    partial class GymPhotos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PowerHouse.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "شارع النصر، المعادي، القاهرة",
                            CreatedAt = new DateTime(2026, 5, 3, 17, 59, 13, 699, DateTimeKind.Utc).AddTicks(1315),
                            Name = "الفرع الرئيسي - المعادي"
                        },
                        new
                        {
                            Id = 2,
                            Address = "شارع عباس العقاد، مدينة نصر، القاهرة",
                            CreatedAt = new DateTime(2026, 5, 3, 17, 59, 13, 699, DateTimeKind.Utc).AddTicks(1462),
                            Name = "فرع مدينة نصر"
                        },
                        new
                        {
                            Id = 3,
                            Address = "شارع 26 يوليو، الزمالك، القاهرة",
                            CreatedAt = new DateTime(2026, 5, 3, 17, 59, 13, 699, DateTimeKind.Utc).AddTicks(1464),
                            Name = "فرع الزمالك"
                        });
                });

            modelBuilder.Entity("PowerHouse.Models.CheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("PowerHouse.Models.GymPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("GymPhotos");
                });

            modelBuilder.Entity("PowerHouse.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("PowerHouse.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "اشتراك شهر واحد - أنسب للمبتدئين",
                            DurationInDays = 30,
                            Name = "شهري",
                            Price = 350m
                        },
                        new
                        {
                            Id = 2,
                            Description = "اشتراك 3 أشهر - وفر 14%",
                            DurationInDays = 90,
                            Name = "ثلاثة أشهر",
                            Price = 900m
                        },
                        new
                        {
                            Id = 3,
                            Description = "اشتراك سنوي - أفضل قيمة، وفر 28%",
                            DurationInDays = 365,
                            Name = "سنوي",
                            Price = 3000m
                        });
                });

            modelBuilder.Entity("PowerHouse.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MainBranchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MainBranchId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 3, 17, 59, 13, 919, DateTimeKind.Utc).AddTicks(319),
                            MainBranchId = 1,
                            Name = "Admin",
                            PasswordHash = "$2a$11$ovoPEWqfpA25kLNlFoVpAuBnhbTi6.cdBF/SDUngkHuatlM1pGNHO",
                            Phone = "01000000000",
                            Role = 1
                        });
                });

            modelBuilder.Entity("PowerHouse.Models.CheckIn", b =>
                {
                    b.HasOne("PowerHouse.Models.Branch", "Branch")
                        .WithMany("CheckIns")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerHouse.Models.User", "User")
                        .WithMany("CheckIns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PowerHouse.Models.GymPhoto", b =>
                {
                    b.HasOne("PowerHouse.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("PowerHouse.Models.Subscription", b =>
                {
                    b.HasOne("PowerHouse.Models.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerHouse.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PowerHouse.Models.User", b =>
                {
                    b.HasOne("PowerHouse.Models.Branch", "MainBranch")
                        .WithMany("Members")
                        .HasForeignKey("MainBranchId");

                    b.Navigation("MainBranch");
                });

            modelBuilder.Entity("PowerHouse.Models.Branch", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("PowerHouse.Models.User", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
